

type WeaponType = "pistol" | "submachinegun" | "rifle" | "shotgun" | "heavyWeapon" | "exotic" | "melee";
type WeaponConcealability = "p" | "j" | "l" | "n";
type WeaponAvailability = "e" | "c" | "p" | "r";
type Ammo = "5mm" | "6mm" | "9mm" | "10mm" | "11mm" | "12mm" | "20mm" | "5.56" | "7.62" | "00" | "";
type WeaponReliability = "vr" | "st" | "ur" | "";
type WeaponCategory =
    "Light Autopistol" | "Medium Autopistol" | "Heavy Autopistol" | "Very Heavy Autopistol" |
    "Light Submachinegun" | "Medium Submachinegun" | "Heavy Submachinegun" |
    "Assault Rifles" | "Shotgun" | "Heavy Weapon" | "Exotic Weapon" | "Melee Weapon";

export type Weapon = {
    id: string;
    category: WeaponCategory;
    name: string;
    description: string;
    type: WeaponType;
    accuracy: number;
    concealability: WeaponConcealability;
    availability: WeaponAvailability;
    damage: string;
    ammo: Ammo;
    shots: number;
    rateOfFire: number;
    reliability: WeaponReliability;
    range: number;
    cost: number;
};

export const pistols: Weapon[] = [
    {
        id: "p1",
        name: "BudgetArms C-13",
        description: "",
        category: "Light Autopistol",
        type: "pistol",
        accuracy: -1,
        concealability: "p",
        availability: "e",
        damage: "1d6",
        ammo: "5mm",
        shots: 8,
        rateOfFire: 2,
        reliability: "st",
        range: 50,
        cost: 75
    },
    {
        id: "p2",
        name: "Dai Lung Cybermag 15",
        description: "",
        category: "Light Autopistol",
        type: "pistol",
        accuracy: -1,
        concealability: "p",
        availability: "c",
        damage: "1d6+1",
        ammo: "6mm",
        shots: 10,
        rateOfFire: 2,
        reliability: "ur",
        range: 50,
        cost: 50
    },
    {
        id: "p3",
        name: "Federated Arms X-22",
        description: "",
        category: "Light Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "p",
        availability: "e",
        damage: "1d6+1",
        ammo: "6mm",
        shots: 10,
        rateOfFire: 2,
        reliability: "st",
        range: 50,
        cost: 150
    },
    {
        id: "p4",
        name: "Militech Arms Avenger",
        description: "",
        category: "Medium Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "e",
        damage: "2d6+1",
        ammo: "9mm",
        shots: 10,
        rateOfFire: 2,
        reliability: "vr",
        range: 50,
        cost: 250
    },
    {
        id: "p5",
        name: "Dai Lung Streetmaster",
        description: "",
        category: "Medium Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "e",
        damage: "2d6+3",
        ammo: "10mm",
        shots: 12,
        rateOfFire: 2,
        reliability: "ur",
        range: 50,
        cost: 250
    },
    {
        id: "p6",
        name: "Federated Arms X-9mm",
        description: "",
        category: "Medium Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "e",
        damage: "2d6+1",
        ammo: "9mm",
        shots: 12,
        rateOfFire: 2,
        reliability: "st",
        range: 50,
        cost: 300
    },
    {
        id: "p7",
        name: "BudgetArms Auto 3",
        description: "",
        category: "Heavy Autopistol",
        type: "pistol",
        accuracy: -1,
        concealability: "j",
        availability: "e",
        damage: "3d6",
        ammo: "11mm",
        shots: 8,
        rateOfFire: 2,
        reliability: "ur",
        range: 50,
        cost: 350
    },
    {
        id: "p8",
        name: "Sternmeyer Type 35",
        description: "",
        category: "Heavy Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "c",
        damage: "3d6",
        ammo: "11mm",
        shots: 8,
        rateOfFire: 2,
        reliability: "vr",
        range: 50,
        cost: 400
    },
    {
        id: "p9",
        name: "Armalite 44",
        description: "",
        category: "Very Heavy Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "e",
        damage: "4d6+1",
        ammo: "12mm",
        shots: 8,
        rateOfFire: 1,
        reliability: "st",
        range: 50,
        cost: 450
    },
    {
        id: "p10",
        name: "Colt AMT Model 2000",
        description: "",
        category: "Very Heavy Autopistol",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "c",
        damage: "4d6+1",
        ammo: "12mm",
        shots: 8,
        rateOfFire: 1,
        reliability: "vr",
        range: 50,
        cost: 500
    }
];

export const machineguns: Weapon[] = [
    {
        id: "m1",
        name: "Uzi Miniauto 9",
        description: "",
        category: "Light Submachinegun",
        type: "submachinegun",
        accuracy: 1,
        concealability: "j",
        availability: "e",
        damage: "2d6+1",
        ammo: "9mm",
        shots: 30,
        rateOfFire: 35,
        reliability: "vr",
        range: 150,
        cost: 475
    },
    {
        id: "m2",
        name: "H&K MP-2013",
        description: "",
        category: "Light Submachinegun",
        type: "submachinegun",
        accuracy: 1,
        concealability: "j",
        availability: "c",
        damage: "2d6+3",
        ammo: "10mm",
        shots: 35,
        rateOfFire: 32,
        reliability: "st",
        range: 150,
        cost: 450
    },
    {
        id: "m3",
        name: "Fed Arms Tech Assault II",
        description: "",
        category: "Light Submachinegun",
        type: "submachinegun",
        accuracy: 1,
        concealability: "j",
        availability: "c",
        damage: "1d6+1",
        ammo: "6mm",
        shots: 50,
        rateOfFire: 25,
        reliability: "st",
        range: 150,
        cost: 400
    },
    {
        id: "m4",
        name: "Arasaka Minami 10",
        description: "",
        category: "Medium Submachinegun",
        type: "submachinegun",
        accuracy: 0,
        concealability: "j",
        availability: "e",
        damage: "2d6+3",
        ammo: "10mm",
        shots: 40,
        rateOfFire: 20,
        reliability: "vr",
        range: 200,
        cost: 500
    },
    {
        id: "m5",
        name: "H&K MPK-9",
        description: "",
        category: "Medium Submachinegun",
        type: "submachinegun",
        accuracy: 1,
        concealability: "j",
        availability: "c",
        damage: "2d6+1",
        ammo: "9mm",
        shots: 35,
        rateOfFire: 25,
        reliability: "st",
        range: 200,
        cost: 520
    },
    {
        id: "m6",
        name: "Sternmeyer SMG 21",
        description: "",
        category: "Heavy Submachinegun",
        type: "submachinegun",
        accuracy: -1,
        concealability: "l",
        availability: "e",
        damage: "3d6",
        ammo: "11mm",
        shots: 30,
        rateOfFire: 15,
        reliability: "vr",
        range: 200,
        cost: 500
    },
    {
        id: "m7",
        name: "H&K MPK-11",
        description: "",
        category: "Heavy Submachinegun",
        type: "submachinegun",
        accuracy: 0,
        concealability: "l",
        availability: "c",
        damage: "4d6+1",
        ammo: "12mm",
        shots: 30,
        rateOfFire: 20,
        reliability: "st",
        range: 200,
        cost: 700
    },
    {
        id: "m8",
        name: "Ingram MAC 14",
        description: "",
        category: "Heavy Submachinegun",
        type: "submachinegun",
        accuracy: -2,
        concealability: "l",
        availability: "e",
        damage: "4d6+1",
        ammo: "12mm",
        shots: 20,
        rateOfFire: 10,
        reliability: "st",
        range: 200,
        cost: 650
    }
];

export const rifles: Weapon[] = [
    {
        id: "r1",
        name: "Militech Ronin Light Assault",
        description: "",
        category: "Assault Rifles",
        type: "rifle",
        accuracy: 1,
        concealability: "n",
        availability: "c",
        damage: "5d6",
        ammo: "5.56",
        shots: 35,
        rateOfFire: 30,
        reliability: "vr",
        range: 400,
        cost: 450
    },
    {
        id: "r2",
        name: "AKR-20 Medium Assault",
        description: "",
        category: "Assault Rifles",
        type: "rifle",
        accuracy: 0,
        concealability: "n",
        availability: "c",
        damage: "5d6",
        ammo: "5.56",
        shots: 30,
        rateOfFire: 30,
        reliability: "st",
        range: 400,
        cost: 500
    },
    {
        id: "r3",
        name: "FN-RAL Heavy Assault Rifle",
        description: "",
        category: "Assault Rifles",
        type: "rifle",
        accuracy: -1,
        concealability: "n",
        availability: "c",
        damage: "6d6+2",
        ammo: "7.62",
        shots: 30,
        rateOfFire: 30,
        reliability: "vr",
        range: 400,
        cost: 600
    },
    {
        id: "r4",
        name: "Kalashnikov A-80 Heavy Rifle",
        description: "",
        category: "Assault Rifles",
        type: "rifle",
        accuracy: -1,
        concealability: "n",
        availability: "e",
        damage: "6d6+2",
        ammo: "7.62",
        shots: 35,
        rateOfFire: 25,
        reliability: "st",
        range: 400,
        cost: 550
    }
];

export const shotgun: Weapon[] = [
    {
        id: "s1",
        name: "Arasaka Rapid Assault 12",
        description: "",
        category: "Shotgun",
        type: "shotgun",
        accuracy: -1,
        concealability: "n",
        availability: "c",
        damage: "4d6",
        ammo: "00",
        shots: 20,
        rateOfFire: 10,
        reliability: "st",
        range: 50,
        cost: 900
    },
    {
        id: "s2",
        name: "Sternmeyer Stakeout 10",
        description: "",
        category: "Shotgun",
        type: "shotgun",
        accuracy: -2,
        concealability: "n",
        availability: "r",
        damage: "4d6",
        ammo: "00",
        shots: 10,
        rateOfFire: 2,
        reliability: "st",
        range: 50,
        cost: 450
    }
];

export const heavyWeapons: Weapon[] = [
    {
        id: "h1",
        name: "Barrett-Arasaka Light 20mm",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "n",
        availability: "r",
        damage: "4d10",
        ammo: "20mm",
        shots: 10,
        rateOfFire: 1,
        reliability: "vr",
        range: 450,
        cost: 2000
    },
    {
        id: "h2",
        name: "Scorpion 16 Missile Launcher",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: -1,
        concealability: "n",
        availability: "r",
        damage: "7d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 1000,
        cost: 3000
    },
    {
        id: "h3",
        name: "Militech Arms RPG-A",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: -1,
        concealability: "n",
        availability: "r",
        damage: "6d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 750,
        cost: 1500
    },
    {
        id: "h4",
        name: "C6 Plastic Explosive 1kg",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: -1,
        concealability: "p",
        availability: "p",
        damage: "8d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 100
    },
    {
        id: "h5",
        name: "Mine",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "j",
        availability: "p",
        damage: "4d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 350
    },
    {
        id: "h6",
        name: "K-A F-253 Flamethrower",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "n",
        availability: "r",
        damage: "2d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "st",
        range: 50,
        cost: 1500
    },
    {
        id: "h7",
        name: "Fragmentation Granade",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "7d10",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 30
    },
    {
        id: "h8",
        name: "Incendiary Granade",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "4d6 for 6 turns",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 30
    },
    {
        id: "h9",
        name: "Stun Granade",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "-5 to stun",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 30
    },
    {
        id: "h10",
        name: "Dazzle Granade",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "blind for 4 turns",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 30
    },
    {
        id: "h11",
        name: "Sonic Granade",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "deafened for 4 turns",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 0,
        cost: 30
    },
    {
        id: "h12",
        name: "Granade Launcher",
        description: "",
        category: "Heavy Weapon",
        type: "heavyWeapon",
        accuracy: 0,
        concealability: "l",
        availability: "r",
        damage: "",
        ammo: "",
        shots: 1,
        rateOfFire: 1,
        reliability: "vr",
        range: 225,
        cost: 150
    }

];

export const exoticWeapons: Weapon[] = [
    {
        id: "e1",
        name: "Techtronica 15 Microwaver",
        description: "",
        category: "Exotic Weapon",
        type: "pistol",
        accuracy: 0,
        concealability: "j",
        availability: "p",
        damage: "1d6",
        ammo: "",
        shots: 10,
        rateOfFire: 2,
        reliability: "vr",
        range: 20,
        cost: 400
    },
    {
        id: "e2",
        name: "Militech Electronic LaserCannon",
        description: "",
        category: "Exotic Weapon",
        type: "rifle",
        accuracy: 0,
        concealability: "n",
        availability: "r",
        damage: "1-5d6",
        ammo: "",
        shots: 10,
        rateOfFire: 2,
        reliability: "ur",
        range: 200,
        cost: 8000
    },
    {
        id: "e3",
        name: "Avante P-1135 Needlegun",
        description: "",
        category: "Exotic Weapon",
        type: "pistol",
        accuracy: 0,
        concealability: "p",
        availability: "p",
        damage: "drugs",
        ammo: "",
        shots: 15,
        rateOfFire: 2,
        reliability: "st",
        range: 40,
        cost: 200
    },
    {
        id: "e4",
        name: "Enertex AKM Power Squirt",
        description: "",
        category: "Exotic Weapon",
        type: "pistol",
        accuracy: -2,
        concealability: "j",
        availability: "c",
        damage: "drugs",
        ammo: "",
        shots: 50,
        rateOfFire: 1,
        reliability: "vr",
        range: 10,
        cost: 15
    },
    {
        id: "e5",
        name: "Nelspot Wombat",
        description: "",
        category: "Exotic Weapon",
        type: "pistol",
        accuracy: -1,
        concealability: "j",
        availability: "c",
        damage: "drugs",
        ammo: "",
        shots: 20,
        rateOfFire: 2,
        reliability: "ur",
        range: 40,
        cost: 200
    },
    {
        id: "e6",
        name: "Militech Electronic Taser",
        description: "",
        category: "Exotic Weapon",
        type: "pistol",
        accuracy: -1,
        concealability: "j",
        availability: "c",
        damage: "stun",
        ammo: "",
        shots: 10,
        rateOfFire: 1,
        reliability: "st",
        range: 10,
        cost: 60
    },
    {
        id: "e7",
        name: "EagleTech Tomcat C-Bow",
        description: "",
        category: "Exotic Weapon",
        type: "exotic",
        accuracy: 0,
        concealability: "n",
        availability: "c",
        damage: "4d6",
        ammo: "",
        shots: 12,
        rateOfFire: 1,
        reliability: "vr",
        range: 150,
        cost: 150
    },
    {
        id: "e8",
        name: "EagleTech Striker X-Bow",
        description: "",
        category: "Exotic Weapon",
        type: "exotic",
        accuracy: -1,
        concealability: "n",
        availability: "c",
        damage: "3d6+3",
        ammo: "",
        shots: 12,
        rateOfFire: 1,
        reliability: "vr",
        range: 50,
        cost: 220
    }
];

export const meleeWeapons: Weapon[] = [
    {
        id: "m1",
        name: "Kendachi Monoknife",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: +1,
        concealability: "p",
        availability: "p",
        damage: "2d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "vr",
        range: 1,
        cost: 200
    },
    {
        id: "m2",
        name: "Kendachi Monokatana",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: +1,
        concealability: "n",
        availability: "r",
        damage: "4d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "vr",
        range: 1,
        cost: 600
    },
    {
        id: "m3",
        name: "SPM-1 Battleglove",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: -2,
        concealability: "n",
        availability: "p",
        damage: "3d6/2d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "vr",
        range: 1,
        cost: 900
    },
    {
        id: "m4",
        name: "Club",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "l",
        availability: "c",
        damage: "1d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 0
    },
    {
        id: "m5",
        name: "Knife",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "p",
        availability: "c",
        damage: "1d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 20
    },
    {
        id: "m6",
        name: "Sword",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "n",
        availability: "c",
        damage: "2d6+2",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 200
    },
    {
        id: "m7",
        name: "Axe",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: -1,
        concealability: "n",
        availability: "c",
        damage: "2d6+3",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 20
    },
    {
        id: "m8",
        name: "Nunchaku/Tonfa",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "l",
        availability: "c",
        damage: "3d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 15
    },
    {
        id: "m9",
        name: "Naginata",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "n",
        availability: "p",
        damage: "3d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 2,
        cost: 100
    },
    {
        id: "m10",
        name: "Shuriken",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "p",
        availability: "c",
        damage: "1d6/3",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 0,
        cost: 3
    },
    {
        id: "m11",
        name: "Switchblade",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "p",
        availability: "c",
        damage: "1d6/2",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 15
    },
    {
        id: "m12",
        name: "Brass Knuckles",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: 0,
        concealability: "p",
        availability: "c",
        damage: "1d6+2",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 10
    },
    {
        id: "m13",
        name: "Sledgehammer",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: -1,
        concealability: "n",
        availability: "c",
        damage: "4d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 1,
        cost: 20
    },
    {
        id: "m14",
        name: "Chainsaw",
        description: "",
        category: "Melee Weapon",
        type: "melee",
        accuracy: -3,
        concealability: "n",
        availability: "c",
        damage: "4d6",
        ammo: "",
        shots: 0,
        rateOfFire: 0,
        reliability: "",
        range: 2,
        cost: 80
    }
];

const ammoList = [
    {
        id: "ammo1",
        name: "box of 100 for light pistol/submachinegun",
        cost: 15
    },
    {
        id: "ammo2",
        name: "box of 50 for medium pistol/submachinegun",
        cost: 15
    },
    {
        id: "ammo3",
        name: "box of 50 for heavy pistol/submachinegun",
        cost: 18
    },
    {
        id: "ammo4",
        name: "box of 50 for very heavy pistol",
        cost: 20
    },
    {
        id: "ammo5",
        name: "box of 100 for assault rifle",
        cost: 40
    },
    {
        id: "ammo6",
        name: "box of 12 for shotgun",
        cost: 15
    },
    {
        id: "ammo7",
        name: "20mm cannon round",
        cost: 25
    },
    {
        id: "ammo8",
        name: "12 arrows",
        cost: 24
    },
    {
        id: "ammo9",
        name: "12 crossbow bolts",
        cost: 24
    },
    {
        id: "ammo10",
        name: "100 airgun pellets",
        cost: 6
    },
    {
        id: "ammo11",
        name: "50 needlegun rounds",
        cost: 6
    }
];